/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedBriowebviewRouteImport } from './routes/_authenticated/briowebview'
import { Route as AuthenticatedRiskObjectRouteImport } from './routes/_authenticated/_risk-object'
import { Route as AuthenticatedRiskObjectVehicleRouteImport } from './routes/_authenticated/_risk-object/vehicle'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBriowebviewRoute =
  AuthenticatedBriowebviewRouteImport.update({
    id: '/briowebview',
    path: '/briowebview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRiskObjectRoute = AuthenticatedRiskObjectRouteImport.update({
  id: '/_risk-object',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRiskObjectVehicleRoute =
  AuthenticatedRiskObjectVehicleRouteImport.update({
    id: '/vehicle',
    path: '/vehicle',
    getParentRoute: () => AuthenticatedRiskObjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/briowebview': typeof AuthenticatedBriowebviewRoute
  '/vehicle': typeof AuthenticatedRiskObjectVehicleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/briowebview': typeof AuthenticatedBriowebviewRoute
  '/vehicle': typeof AuthenticatedRiskObjectVehicleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/_risk-object': typeof AuthenticatedRiskObjectRouteWithChildren
  '/_authenticated/briowebview': typeof AuthenticatedBriowebviewRoute
  '/_authenticated/_risk-object/vehicle': typeof AuthenticatedRiskObjectVehicleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/briowebview' | '/vehicle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/briowebview' | '/vehicle'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/_risk-object'
    | '/_authenticated/briowebview'
    | '/_authenticated/_risk-object/vehicle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/briowebview': {
      id: '/_authenticated/briowebview'
      path: '/briowebview'
      fullPath: '/briowebview'
      preLoaderRoute: typeof AuthenticatedBriowebviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_risk-object': {
      id: '/_authenticated/_risk-object'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRiskObjectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_risk-object/vehicle': {
      id: '/_authenticated/_risk-object/vehicle'
      path: '/vehicle'
      fullPath: '/vehicle'
      preLoaderRoute: typeof AuthenticatedRiskObjectVehicleRouteImport
      parentRoute: typeof AuthenticatedRiskObjectRoute
    }
  }
}

interface AuthenticatedRiskObjectRouteChildren {
  AuthenticatedRiskObjectVehicleRoute: typeof AuthenticatedRiskObjectVehicleRoute
}

const AuthenticatedRiskObjectRouteChildren: AuthenticatedRiskObjectRouteChildren =
  {
    AuthenticatedRiskObjectVehicleRoute: AuthenticatedRiskObjectVehicleRoute,
  }

const AuthenticatedRiskObjectRouteWithChildren =
  AuthenticatedRiskObjectRoute._addFileChildren(
    AuthenticatedRiskObjectRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedRiskObjectRoute: typeof AuthenticatedRiskObjectRouteWithChildren
  AuthenticatedBriowebviewRoute: typeof AuthenticatedBriowebviewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedRiskObjectRoute: AuthenticatedRiskObjectRouteWithChildren,
  AuthenticatedBriowebviewRoute: AuthenticatedBriowebviewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
